name: Build and Deploy
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.1]
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@main
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: IsseiClockWise/vuepress-starter
        TARGET_BRANCH: main
        BUILD_SCRIPT: npm init && npm run build
        BUILD_DIR: src/.vuepress/dist
        # CNAME: https://www.xxx.com