name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: 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
        TARGET_REPO: IsseiClockWise/vuepress-starter
        TARGET_BRANCH: main
        BUILD_SCRIPT: npm && npm src:build
        BUILD_DIR: src/.vuepress/dist
        CNAME: https://www.xxx.com