name: Build and Deploy
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.1]
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install  # このステップで依存関係をインストールする

    - name: Build VuePress site
      run: npm run build  # ビルドスクリプトを実行する

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: IsseiClockWise/vuepress-starter
        TARGET_BRANCH: main
        BUILD_DIR: src/.vuepress/dist
        # CNAME: https://www.xxx.com
